apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook-cluster
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: '{{nameNormalized}}-guestbook'
      labels:
        app: guestbook
        generators-type: cluster
    spec:
      project: "default"
      source:
        repoURL: https://github.com/xyang0917/argocd-example-apps/
        targetRevision: HEAD
        path: guestbook
      destination:
        server: '{{server}}'
        namespace: guestbook
