apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - list:
      elements:
      - cluster: engineering-dev
        url: https://kubernetes.default.svc
      - cluster: engineering-prod
        url: https://172.16.203.52:6443
  template:
    metadata:
      name: '{{cluster}}-guestbook'
      labels:
        app: guestbook
    spec:
      project: default
      source:
        repoURL: https://github.com/xyang0917/applicationset.git
        targetRevision: HEAD
        path: examples/list-generator/guestbook/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: guestbook
